parameters:
#    slik_dompdf.example.class: LilaConcepts\SlikDompdfBundle\Example

services:
#    slik_dompdf.example:
#        class: %slik_dompdf.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
